on: [push]

jobs:
  check-quality:
    runs-on: ubuntu-latest
    name: check-quality
    steps:
      - name: Check code meets quality standards
        id: codiga
        uses: codiga/github-action@master
        with:
          repo_token: ${{ secrets.DYORM_GITHUB_TOKEN }}
          codiga_api_token: ${{ secrets.CODIGA_API_TOKEN }}
          force_ref: 'none'
          min_quality_grade: 'WARNING'
          min_quality_score: '80'
          max_defects_rate: '0.001'
          max_complex_functions_rate: '0.001'
          max_long_functions_rate: '0.15'
          project_name: ''
          max_timeout_sec: '600'